Friend Module Constants
    Friend Const AbandonGameText = "Abandon Game"
    Friend Const DropText = "Drop"
    Friend Const GameMenuText = "Game Menu"
    Friend Const GoBackText = "Go Back"
    Friend Const GroundText = "Ground"
    Friend Const InventoryText = "Inventory"
    Friend Const MoveText = "Move"
    Friend Const NoText = "No"
    Friend Const QuestsText = "Quests"
    Friend Const QuitText = "Quit"
    Friend Const StartGameText = "Start Game"
    Friend Const TalkText = "Talk"
    Friend Const YesText = "Yes"
End Module
